services:
  mysql:
    build: .
    restart: no
    container_name: gatekeeper_mysql_django
    env_file:
      - .env
    ports:
      - "3312:3306"
    volumes:
      - mysql_data_gatekeeper_django:/var/lib/mysql
    networks:
      - shared_network_gatekeeper

  phpmyadmin_gatekeeper:
    image: phpmyadmin/phpmyadmin
    container_name: gatekeeper_phpmyadmin_django
    restart: no
    env_file:
      - .env
    ports:
      - "8088:80"
    networks:
      - shared_network_gatekeeper
    depends_on:
      - mysql

volumes:
  mysql_data_gatekeeper_django: {}

networks:
  shared_network_gatekeeper:
    driver: bridge
