version: '3.9'

services:
  mysql_gatekeeper:
    build: .
    restart: always
    container_name: mysql_gatekeeper_container
    env_file:
      - .env
    ports:
      - "3310:3306"
    volumes:
      - mysql_data_gatekeeper:/var/lib/mysql
    networks:
      - shared_network_gatekeeper

  phpmyadmin_gatekeeper:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_gatekeeper_container
    restart: always
    env_file:
      - .env
    ports:
      - "8087:80"
    networks:
      - shared_network_gatekeeper
    depends_on:
      - mysql_gatekeeper

volumes:
  mysql_data_gatekeeper: {}

networks:
  shared_network_gatekeeper:
    driver: bridge
    external: true
