# Generated by Django 5.1.4 on 2025-08-12 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aegis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedAccess',
            fields=[
                ('status', models.SmallIntegerField(choices=[(1, 'Active'), (0, 'Inactive'), (2, 'Deleted')], default=1, verbose_name='Status')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.AutoField(db_column='id', db_index=True, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('jti', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Access JTI')),
                ('expires_at', models.DateTimeField(verbose_name='Expires At')),
                ('blacklisted_at', models.DateTimeField(auto_now_add=True, verbose_name='Blacklisted At')),
            ],
            options={
                'verbose_name': 'Blacklisted Access Token',
                'verbose_name_plural': 'Blacklisted Access Tokens',
                'db_table': 'blacklisted_access_tokens',
                'indexes': [models.Index(fields=['expires_at'], name='blacc_exp_idx')],
            },
        ),
        migrations.CreateModel(
            name='BlacklistedRefresh',
            fields=[
                ('status', models.SmallIntegerField(choices=[(1, 'Active'), (0, 'Inactive'), (2, 'Deleted')], default=1, verbose_name='Status')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.AutoField(db_column='id', db_index=True, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('rjti', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Refresh JTI')),
                ('expires_at', models.DateTimeField(verbose_name='Expires At')),
                ('blacklisted_at', models.DateTimeField(auto_now_add=True, verbose_name='Blacklisted At')),
            ],
            options={
                'verbose_name': 'Blacklisted Refresh Token',
                'verbose_name_plural': 'Blacklisted Refresh Tokens',
                'db_table': 'blacklisted_refresh_tokens',
                'indexes': [models.Index(fields=['expires_at'], name='blref_exp_idx')],
            },
        ),
    ]
