# Generated by Django 5.1.4 on 2025-08-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aegis', '0003_servicemaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicemaster',
            name='service_code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
