# Generated by Django 5.1.4 on 2025-08-30 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aegis', '0004_alter_servicemaster_service_code'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='permissionmaster',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='permissionmaster',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aegis.servicemaster'),
        ),
        migrations.RemoveField(
            model_name='permissionmaster',
            name='menu',
        ),
        migrations.CreateModel(
            name='GroupServiceAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(1, 'Active'), (0, 'Inactive'), (2, 'Deleted')], default=1, verbose_name='Status')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_links', to='auth.group')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_links', to='aegis.servicemaster')),
            ],
            options={
                'verbose_name': 'Group Service Access',
                'verbose_name_plural': 'Group Services Access',
                'db_table': 'group_service_access',
                'unique_together': {('group', 'service')},
            },
        ),
    ]
